version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

